ALTER TABLE emp ADD COLUMN post_no VARCHAR(7);
ALTER TABLE emp ALTER COLUMN comm SET DEFAULT 0;
UPDATE emp SET comm = 0 WHERE comm IS NULL;
ALTER TABLE emp ALTER COLUMN comm SET NOT NULL;
ALTER TABLE dept RENAME COLUMN deptno TO dno;

